[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/docs"
  to = "/docs/index"
  status = 301

[[redirects]]
  from = "/learn"
  to = "/learn/index"
  status = 301
